# Set theme
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[window]
startup_mode = "Fullscreen"
padding = { x = 3, y = 3 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[env]
TERM = "alacritty"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 15.0
