# Set theme
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[window]
startup_mode = "Fullscreen"
padding = { x = 10, y = 10 }

[env]
TERM = "alacritty"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14.0
